default: &default
  adapter: mysql2
  encoding: utf8
  host: mysql
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
